### ISSUE TITLE
customElements is undefined

### ISSUE THREAD

**Issue by Draeken** [hotforfeature/angular-polymer-starter-kit#4]
When I launch `npm run start:es5`
on Firefox 59.
This happens before `webcomponentReady` resolved, due to polymer element import in `app.component.ts`

**Comment by hotforfeature** [comment]
Thanks for the report! 

I've updated `main.ts` to dynamically import `AppModule` instead of importing it synchronously before the WebcomponentsReady event. I've also added comments as to why this is needed and an alternative way of importing the main component that uses Polymer.

Let me know if you have any questions!

**Comment by Draeken** [comment]
Awesome! Thanks!

**Comment by varletconst** [comment]
Hi,
Error is still present when using `--prod` flag (Firefox)

**Comment by hotforfeature** [comment]
@varletconst I've updated the repo, try pulling it again

**Comment by varletconst** [comment]
It works well in prod mode but throw in dev mode.
Using `require` works in both mode
